/* global BOX_CAMPUS_SAMPLE */
var BOX_CAMPUS_SAMPLE = {
  id: "sample-photo-exposure",
  title: "사진의 노출",
  origin: "authored-sample",
  weeks: [
    {
      id: "w1",
      number: 1,
      title: "빛의 양",
      promise: "노출 삼각형과 손떨림을 손에 익힌다",
      ideaIds: ["idea-a", "idea-b"],
    },
    {
      id: "w2",
      number: 2,
      title: "초점",
      promise: "피사계 심도와 초점 거리",
      ideaIds: [],
    },
    {
      id: "w3",
      number: 3,
      title: "색",
      promise: "화이트밸런스와 색온도",
      ideaIds: [],
    },
    {
      id: "w4",
      number: 4,
      title: "구도",
      promise: "시선을 이끄는 프레임",
      ideaIds: [],
    },
    {
      id: "w5",
      number: 5,
      title: "빛과 그림자",
      promise: "방향과 질감",
      ideaIds: [],
    },
    {
      id: "w6",
      number: 6,
      title: "한 장으로 말하기",
      promise: "주제를 한 컷에 담기",
      ideaIds: [],
    },
  ],
  ideas: [
    { id: "idea-a", title: "노출은 빛의 양", weekId: "w1" },
    { id: "idea-b", title: "손털림", weekId: "w1" },
  ],
  cards: [
    {
      role: "librarian",
      id: "lib-a",
      ideaId: "idea-a",
      thesis:
        "같은 밝기는 조리개, 셔터, ISO 세 손잡이로 맞춘다. 하나를 밝게 하면 다른 하나를 그만큼 어둡게 해야 화면이 같다.",
      source: { label: "노출 삼각형. 사진 기초에서 공통으로 쓰는 모형." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-a",
      ideaId: "idea-a",
      question: "셔터를 두 배 빠르게 하면 빛은?",
      choices: [
        "두 배로 늘어난다",
        "반으로 줄어든다",
        "그대로다",
        "ISO가 올라간다",
      ],
      correctIndex: 1,
      reveal: "셔터 속도가 두 배가 되면 빛이 들어오는 시간이 반이 된다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-a",
      ideaId: "idea-a",
      thesis: "배경을 흐리게 하려면 조리개를 조인다.",
      holeLabel: "방향이 반대다",
      patches: ["조리개를 연다", "셔터를 더 느리게 한다", "ISO를 내린다"],
      correctIndex: 0,
      reveal: "열린 조리개가 초점 밖을 흐린다. 조이면 더 선명해진다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-a",
      ideaId: "idea-a",
      foreignField: "요리",
      analogy: "같은 익힘은 불 세기 곱하기 시간이다. 불을 올리면 시간을 줄인다.",
      analogyLimit: "음식은 타고 사진은 밝은 곳이 날아간다.",
      provenance: "authored",
    },
    {
      role: "librarian",
      id: "lib-b",
      ideaId: "idea-b",
      thesis:
        "손으로 지탬 때 대략적 한계는 1 나누기 초점거리 초다. 50mm면 1/50초보다 느리면 손이 남는다.",
      source: { label: "손떨림 한계. 광각에 따라 조금 달라지는 경험칙." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-b",
      ideaId: "idea-b",
      question: "100mm 렌즈에서 손털림을 줄이려면?",
      choices: [
        "1/50초",
        "1/100초보다 빠르게",
        "1초",
        "ISO 100 고정",
      ],
      correctIndex: 1,
      reveal: "초점거리가 길어지면 허용 시간도 짧아진다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-b",
      ideaId: "idea-b",
      thesis: "흔들리면 ISO를 내린다.",
      holeLabel: "손잡이가 반대다",
      patches: [
        "셔터를 빠르게 하거나 ISO를 올린다",
        "조리개를 조인다",
        "플래시를 끄다",
      ],
      correctIndex: 0,
      reveal: "흔들림에는 셔터를 빠르게 하거나 ISO를 올린다. ISO를 내리면 더 흔들린다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-b",
      ideaId: "idea-b",
      foreignField: "스포츠",
      analogy: "빠른 공에 셔터를 맞추는 것과 같다.",
      analogyLimit:
        "스포츠는 피사체가 움직이고 이 장면은 카메라가 움직인다.",
      provenance: "authored",
    },
  ],
};
