import type { CampusInput } from "./types";

export const BOX_CAMPUS_SAMPLE = {
  id: "sample-photo-exposure",
  title: "사진의 노출",
  origin: "authored-sample",
  weeks: [
    {
      id: "w1",
      number: 1,
      title: "빛의 양",
      promise: "노출 삼각형과 손떨림을 손에 익힌다",
      ideaIds: ["idea-a", "idea-b"],
    },
    {
      id: "w2",
      number: 2,
      title: "초점",
      promise: "조리개와 피사계 심도",
      ideaIds: ["idea-c"],
    },
    {
      id: "w3",
      number: 3,
      title: "색",
      promise: "화이트밸런스와 색온도",
      ideaIds: ["idea-d"],
    },
    {
      id: "w4",
      number: 4,
      title: "구도",
      promise: "시선을 이끄는 프레임",
      ideaIds: ["idea-e"],
    },
    {
      id: "w5",
      number: 5,
      title: "빛과 그림자",
      promise: "방향과 질감",
      ideaIds: ["idea-f"],
    },
    {
      id: "w6",
      number: 6,
      title: "한 장으로 말하기",
      promise: "주제를 한 컷에 담기",
      ideaIds: [],
    },
  ],
  ideas: [
    { id: "idea-a", title: "노출은 빛의 양", weekId: "w1" },
    { id: "idea-b", title: "손떨림", weekId: "w1" },
    { id: "idea-c", title: "피사계 심도", weekId: "w2" },
    { id: "idea-d", title: "화이트밸런스", weekId: "w3" },
    { id: "idea-e", title: "시선은 빈 곳으로", weekId: "w4" },
    { id: "idea-f", title: "옆에서 온 빛", weekId: "w5" },
  ],
  cards: [
    {
      role: "librarian",
      id: "lib-a",
      ideaId: "idea-a",
      thesis:
        "같은 밝기는 조리개, 셔터, ISO 세 손잡이로 맞춘다. 하나를 밝게 하면 다른 하나를 그만큼 어둡게 해야 화면이 같다.",
      source: { label: "노출 삼각형. 사진 기초에서 공통으로 쓰는 모형." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-a",
      ideaId: "idea-a",
      question: "셔터를 두 배 빠르게 하면 빛은?",
      choices: [
        "두 배로 늘어난다",
        "반으로 줄어든다",
        "그대로다",
        "ISO가 올라간다",
      ],
      correctIndex: 1,
      reveal: "셔터 속도가 두 배가 되면 빛이 들어오는 시간이 반이 된다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-a",
      ideaId: "idea-a",
      thesis: "배경을 흐리게 하려면 조리개를 조인다.",
      holeLabel: "방향이 반대다",
      patches: ["조리개를 연다", "셔터를 더 느리게 한다", "ISO를 내린다"],
      correctIndex: 0,
      reveal: "열린 조리개가 초점 밖을 흐린다. 조이면 더 선명해진다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-a",
      ideaId: "idea-a",
      foreignField: "요리",
      analogy: "같은 익힘은 불 세기 곱하기 시간이다. 불을 올리면 시간을 줄인다.",
      analogyLimit: "음식은 타고 사진은 밝은 곳이 날아간다.",
      provenance: "authored",
    },
    {
      role: "librarian",
      id: "lib-b",
      ideaId: "idea-b",
      thesis:
        "손으로 잡을 때 대략적 한계는 1 나누기 초점거리 초다. 50mm면 1/50초보다 느리면 손이 남는다.",
      source: { label: "손떨림 한계. 광각에 따라 조금 달라지는 경험칙." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-b",
      ideaId: "idea-b",
      question: "100mm 렌즈에서 손떨림을 줄이려면?",
      choices: [
        "1/50초",
        "1/100초보다 빠르게",
        "1초",
        "ISO 100 고정",
      ],
      correctIndex: 1,
      reveal: "초점거리가 길어지면 허용 시간도 짧아진다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-b",
      ideaId: "idea-b",
      thesis: "흔들리면 ISO를 내린다.",
      holeLabel: "손잡이가 반대다",
      patches: [
        "셔터를 빠르게 하거나 ISO를 올린다",
        "조리개를 조인다",
        "플래시를 끄다",
      ],
      correctIndex: 0,
      reveal: "흔들림에는 셔터를 빠르게 하거나 ISO를 올린다. ISO를 내리면 더 흔들린다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-b",
      ideaId: "idea-b",
      foreignField: "스포츠",
      analogy: "빠른 공에 셔터를 맞추는 것과 같다.",
      analogyLimit:
        "스포츠는 피사체가 움직이고 이 장면은 카메라가 움직인다.",
      provenance: "authored",
    },
    {
      role: "librarian",
      id: "lib-c",
      ideaId: "idea-c",
      thesis:
        "조리개 숫자가 작을수록 구멍이 크다. 초점이 맞은 면의 앞뒤가 더 빨리 흐려진다.",
      source: { label: "피사계 심도. f 숫자가 작으면 배경이 더 흐리다." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-c",
      ideaId: "idea-c",
      question: "f/2와 f/8 중 배경이 더 흐린 쪽은?",
      choices: ["f/8", "f/2", "둘 다 같다", "셔터에 달렸다"],
      correctIndex: 1,
      reveal: "f/2가 구멍이 더 커서, 초점면 밖이 더 많이 흐려진다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-c",
      ideaId: "idea-c",
      thesis: "배경을 선명하게 하려면 조리개를 연다.",
      holeLabel: "방향이 반대다",
      patches: ["조리개를 조여 f 숫자를 키운다", "ISO만 올린다", "초점을 배경 밖으로 뺀다"],
      correctIndex: 0,
      reveal: "배경까지 선명하려면 조리개를 조인다. 열면 더 흐려진다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-c",
      ideaId: "idea-c",
      foreignField: "음악",
      analogy: "한 악기를 앞으로 내면 나머지가 뒤로 물러난다.",
      analogyLimit: "소리는 섞이고, 사진은 맞은 초점면이 있다.",
      provenance: "authored",
    },
    {
      role: "librarian",
      id: "lib-d",
      ideaId: "idea-d",
      thesis:
        "같은 흰색도 전구 아래에서는 주황으로 찍힌다. 화이트밸런스는 그 조명에서 흰 점을 고른다.",
      source: { label: "화이트밸런스. 조명의 색을 기준으로 흰색을 맞춘다." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-d",
      ideaId: "idea-d",
      question: "전구 빛에서 낮 기준으로 찍으면 화면은?",
      choices: ["파래진다", "주황에 가깝다", "흑백이 된다", "초점이 나간다"],
      correctIndex: 1,
      reveal: "낮 기준은 전구의 주황을 그대로 남긴다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-d",
      ideaId: "idea-d",
      thesis: "차갑게 보이면 색온도 숫자를 내린다.",
      holeLabel: "숫자를 내리면 더 파래진다",
      patches: ["색온도를 올려 노란 쪽을 더한다", "ISO를 올린다", "셔터를 느리게 한다"],
      correctIndex: 0,
      reveal: "차갑게 보일 때는 색온도를 올려 노란 빛을 더한다. 내리면 더 파래진다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-d",
      ideaId: "idea-d",
      foreignField: "요리",
      analogy: "같은 소금도 국물에 따라 간이 달라 보인다.",
      analogyLimit: "간은 맛이고, 화이트밸런스는 색의 기준점이다.",
      provenance: "authored",
    },
    {
      role: "librarian",
      id: "lib-e",
      ideaId: "idea-e",
      thesis: "주제를 한가운데만 두면 눈이 그 점에서 멈춘다. 반대편을 비우면 시선이 그 빈 곳으로 들어온다.",
      source: { label: "구도. 여백은 빈 구멍이 아니라 시선이 가는 길이다." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-e",
      ideaId: "idea-e",
      question: "주제를 프레임 한가운데 두면 시선은?",
      choices: ["빈 곳으로 흐른다", "그 점에서 멈춘다", "프레임 밖으로 나간다", "초점이 풀린다"],
      correctIndex: 1,
      reveal: "한가운데는 눈이 머물 곳이 그 점뿐이다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-e",
      ideaId: "idea-e",
      thesis: "주제를 가장자리에 붙여야 안정된다.",
      holeLabel: "잘리면 답답해진다",
      patches: ["가장자리 안쪽에 두고 반대편을 비운다", "정가운데로 옮긴다", "주제를 프레임 밖으로 자른다"],
      correctIndex: 0,
      reveal: "여백을 남기되 주제는 잘리지 않게 안쪽에 둔다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-e",
      ideaId: "idea-e",
      foreignField: "요리",
      analogy: "접시에 음식을 한쪽으로 놓으면 나머지 여백이 보이게 한다.",
      analogyLimit: "접시의 여백은 맛에 안 들어가고, 프레임의 여백은 잘리면 주제가 사라진다.",
      provenance: "authored",
    },
    {
      role: "librarian",
      id: "lib-f",
      ideaId: "idea-f",
      thesis: "정면 빛은 그림자를 지워 얼굴을 평평하게 만든다. 옆에서 온 빛은 코와 볼의 그림자로 입체감을 만든다.",
      source: { label: "빛의 방향. 정면등은 평평하고 측면광은 윤곽을 만든다." },
      provenance: "authored",
    },
    {
      role: "tutor",
      id: "tutor-f",
      ideaId: "idea-f",
      question: "얼굴을 입체적으로 보이게 하려면?",
      choices: ["정면 플래시", "옆에서 온 빛", "노출을 낮춘다", "초점거리를 줄인다"],
      correctIndex: 1,
      reveal: "옆빛은 그림자를 남겨 볼과 코의 높이를 보여 준다.",
      provenance: "authored",
    },
    {
      role: "editor",
      id: "editor-f",
      ideaId: "idea-f",
      thesis: "그림자가 진하면 빛을 피사체 정면으로 옮긴다.",
      holeLabel: "정면으로 옮기면 더 평평해진다",
      patches: ["빛은 옆에 두고 반사로 그림자만 연하게 한다", "플래시를 정면에 켠다", "ISO를 내린다"],
      correctIndex: 0,
      reveal: "방향은 옆으로 두고, 반대편만 조금 밝혀 그림자를 연하게 한다.",
      provenance: "authored",
    },
    {
      role: "roommate",
      id: "room-f",
      ideaId: "idea-f",
      foreignField: "연극",
      analogy: "무대 조명이 옆에서 오면 배우의 윤곽이 살고, 정면등은 얼굴을 하얗게 지운다.",
      analogyLimit: "무대는 관객이 멀고, 사진은 가까이서 그림자가 눈을 가릴 수 있다.",
      provenance: "authored",
    },
  ],
} satisfies CampusInput;
